### ISSUE TITLE
『服务集成』 - 新建 服务集成条目时 未保存配置前，点击『测试连接』报错

### ISSUE THREAD

**Issue by colynn** [go-atomci/atomci-press#11]
* `应用版本`:
     * `atomci-frontend`: 1.1.0
     * `atomci`: 1.1.0
* `Kubernetes`: v1.18.5

**Comment by colynn** [comment]
已修改 『测试连接』的请求路由， 请拉取 最新的镜像，修复此问题。 
`colynn/atomci:1.2.0`
`colynn/atomci-frontend:1.2.0`

## docker-compose 部署方式下- 更新说明

1. 确认 `docker-compose.yml` 的镜像的版本，调整为 `1.2.0` 或是 `latest`

```yaml
version: '3'

services:
  frontend:
    image: colynn/atomci-frontend:1.2.0
    container_name: "frontend"
    networks:
        - node-network
    ports:
      - "8090:8090"
    volumes:
      - "./nginx:/etc/nginx/conf.d"

  atomci:
    image: colynn/atomci:1.2.0
    container_name: "atomci"
    depends_on:
      - mysql
    networks:
      - node-network
    ports:
      - "8080:8080"
    environment:
      - ENV=prod
    volumes:
      - "./conf/app.conf:/atomci/conf/app.conf"
      - "./conf/rbac_policy.csv:/atomci/conf/rbac_policy.csv"
      - "./conf/k8sconfig:/atomci/conf/k8sconfig"
      - "/etc/localtime:/etc/localtime"
      - "/usr/share/zoneinfo/Asia/Shanghai:/usr/share/zoneinfo/Asia/Shanghai"
  
  mysql:
    image: mysql:5.7.35
    container_name: mysql
    networks:
      - node-network    
    restart: always
    volumes:
        - "./mysql/my.cnf:/etc/mysql/my.cnf"
        - "./mysql/data:/var/lib/mysql"
    environment:
        MYSQL_DATABASE: atomci
        MYSQL_ROOT_PASSWORD: 123456

networks:
  node-network:
    driver: bridge
```
