### ISSUE TITLE
如果更新服务-升级版本

### ISSUE THREAD

**Issue by colynn** [go-atomci/atomci-press#12]
## docker-compose 部署方式- 更新说明

1. 确认 `docker-compose.yml` 的镜像的版本，调整为 `1.2.0` 或是 `latest`

```yaml
version: '3'

services:
  frontend:
    image: colynn/atomci-frontend:1.2.0
    container_name: "frontend"
    networks:
        - node-network
    ports:
      - "8090:8090"
    volumes:
      - "./nginx:/etc/nginx/conf.d"

  atomci:
    image: colynn/atomci:1.2.0
    container_name: "atomci"
    depends_on:
      - mysql
    networks:
      - node-network
    ports:
      - "8080:8080"
    environment:
      - ENV=prod
    volumes:
      - "./conf/app.conf:/atomci/conf/app.conf"
      - "./conf/rbac_policy.csv:/atomci/conf/rbac_policy.csv"
      - "./conf/k8sconfig:/atomci/conf/k8sconfig"
      - "/etc/localtime:/etc/localtime"
      - "/usr/share/zoneinfo/Asia/Shanghai:/usr/share/zoneinfo/Asia/Shanghai"
  
  mysql:
    image: mysql:5.7.35
    container_name: mysql
    networks:
      - node-network    
    restart: always
    volumes:
        - "./mysql/my.cnf:/etc/mysql/my.cnf"
        - "./mysql/data:/var/lib/mysql"
    environment:
        MYSQL_DATABASE: atomci
        MYSQL_ROOT_PASSWORD: 123456

networks:
  node-network:
    driver: bridge
```

2.  拉取镜像并重建服务

```sh
$ docker-compose pull atomci fronend
$ docker-compose up -d atomci frontend
```
