### ISSUE TITLE
后端服务重启后，k8s conf文件丢失

### ISSUE THREAD

**Issue by colynn** [go-atomci/atomci-press#5]
版本：1.0.1
部署方式： docker-compose

解决方案：

可以将 k8sconfig也挂载出来， 添加如下
```yaml
      - "./conf/k8sconfig:/atomci/conf/k8sconfig"
```

修改的后端服务 __atomci__ docker-compose 配置如下：

```yml
  atomci:
    image: colynn/atomci:1.0.0
    container_name: "atomci"
    depends_on:
      - mysql
    networks:
      - node-network
    ports:
      - "8080:8080"
    environment:
      - ENV=prod
    volumes:
      - "./conf/app.conf:/atomci/conf/app.conf"
      - "./conf/rbac_policy.csv:/atomci/conf/rbac_policy.csv"
      - "./conf/k8sconfig:/atomci/conf/k8sconfig"
      - "/etc/localtime:/etc/localtime"
      - "/usr/share/zoneinfo/Asia/Shanghai:/usr/share/zoneinfo/Asia/Shanghai"
```
